version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/deploy/terraform/sub/core/infra"
    schedule:
      interval: "daily"
      timezone: "Europe/London"
    open-pull-requests-limit: 3
